### ISSUE TITLE
Automated Tests

### ISSUE THREAD

**Issue by tearodactyl** [zerocurrencycoin/Zero#15]
Zcash comes with [several suites of tests](https://github.com/zcash/zcash/blob/master/doc/unit-tests.md). These may never have passed entirely on Zero, but should be engaged periodically and results reviewed. At a minimum, with upcoming changes we should not brake any tests that are passing now. Also, tests were developed for other Z coins to support recent forks and fixes. We may want to pick those up as well.

**full_test_suite**.py fails on 2 tests:
equihash_tests
joinsplit

It then blocks on paymentdisclosure.py
```
Initializing test directory /tmp/testPDw1_E
zcashd: main.cpp:1528: void InvalidChainFound(CBlockIndex*): Assertion `tip' failed.
Traceback (most recent call last):
  File "/home/devl/zero/Zero/qa/rpc-tests/paymentdisclosure.py", line 215, in <module>
  File "./full_test_suite.py", line 201, in <module>
```

**rpc-tests**.sh fails in the similar fashion, and should be re-run in the fresh build environment.
```
=== Running testscript paymentdisclosure.py ===
Initializing test directory /tmp/testOwML22
zcashd: main.cpp:1528: void InvalidChainFound(CBlockIndex*): Assertion `tip' failed.

```

**Comment by tearodactyl** [comment]
For the Python-based tests, "pip install pyblake2"

**Comment by CryptoForge** [comment]
The joinsplit gtest issues have been resolved. These errors were due to the joinsplit returning different error messages than expected because of the size of the max_money constant and the assumed values that would create certain errors based on a 21M supply.

**Comment by CryptoForge** [comment]
Most of the RPC test error appear to be due to the 720 block maturity of ZERO vs the 100 block maturity of ZCash. These test do not appear to have been updated from the original zcash codebase.
